remote_theme: "mmistakes/minimal-mistakes@4.19.3"

# Plugins
plugins:
  - jekyll-include-cache

title: GIScience TeachR
description: >- # this means to ignore newlines until "baseurl:"
  Resiliant GIScience Education in R
search: true

include:
  - _pages

author:
  name   : "Stefano De Sabbata"
  avatar : "/assets/images/Stefano_DeSabbata_August2019_small_square.jpg"
  bio    : "Lecturer in Quantitative Geography at the University of Leicester, Research Associate at the Oxford Internet Institute"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://stefanodesabbata.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sdesabbata"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://https://twitter.com/maps4thought"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maps4thought"

footer:
  links:
    - label: "Website"
      icon: "fab fa-fw fa-link"
      url: "https://https://twitter.com/maps4thought"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/globalgiscienceeducation"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
